using ProjectEulerUtilities;
using System.Diagnostics;

#region Calling the Methods
// Uncomment the calls to the method(s) you want to execute
//Problem1();
Problem2();

#endregion

#region Method Definitions
static void ProblemN()
{
    // Copy the problem text here.
    Stopwatch executionTimer = Stopwatch.StartNew();
    int answer = 0;

    // 
    // add code here
    //

    Console.WriteLine($"Answer = {answer}");
    Console.WriteLine($"Execution time = {executionTimer.ElapsedMilliseconds} ms");
}

static void Problem1()
{
    // If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    // Find the sum of all the multiples of 3 or 5 below 1000.
    Stopwatch executionTimer = Stopwatch.StartNew();
    int sum = 0;
    for (int i = 1; i <= 1000; i++)
    {
        if (NumericUtils.IsXDivisibleByY(i,3))
        {
            sum += i;
        }
        else if (NumericUtils.IsXDivisibleByY(i, 5))
        {
            sum += i;
        }
    }
    Console.WriteLine($"Answer = {sum}");
    Console.WriteLine($"Execution time = {executionTimer.ElapsedMilliseconds} ms");
}

static void Problem2()
{
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    Stopwatch executionTimer = Stopwatch.StartNew();
    ulong answer = 0;

    List<ulong> fibonacciTerms = NumericUtils.GetFibonacciSeries(4000000);
    foreach (ulong fibonacciTerm in fibonacciTerms)
    {
        if (fibonacciTerm % 2 == 0)
        {
            answer += fibonacciTerm;
        }
    }

    Console.WriteLine($"Answer = {answer}");
    Console.WriteLine($"Execution time = {executionTimer.ElapsedMilliseconds} ms");
}
#endregion